# -*- coding: utf-8 -*-
"""api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zY5cHBh3Wfn_ORms_P19tv3T21FIRZwu
"""

!pip install flask numpy pandas scikit-learn joblib pyngrok

from flask import Flask, request, jsonify
import pandas as pd
import joblib
import numpy as np
from pyngrok import ngrok

app = Flask(__name__)

model = joblib.load('best_rf_model.joblib')

@app.route('/predict', methods=['POST'])
def predict():
    # รับข้อมูลจาก request
    data = request.json

    # แปลงข้อมูลเป็น DataFrame
    df = pd.DataFrame(data, index=[0])

    # ทำนายผลลัพธ์
    prediction = model.predict(df)

    # ส่งผลลัพธ์กลับ
    return jsonify({'prediction': int(prediction[0])})

# ตั้งค่า authtoken สำหรับ ngrok (แทนที่ด้วย authtoken ของคุณ)
ngrok.set_auth_token('31HDyiecQxEopS5jfq7nGEXZEpY_3oZFMd3isMWv2AUE6zjge')

# เริ่มต้น Flask app และ ngrok
if __name__ == '__main__':
    # เริ่ม ngrok
    public_url = ngrok.connect(5000)
    print(f'Public URL: {public_url}')

    # เริ่ม Flask app
    app.run(host='0.0.0.0', port=5000)